image: maven:3.5.4-jdk-8-alpine

#include:
#  - template: Code-Quality.gitlab-ci.yml

variables:
  MC_MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  MC_MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode"


before_script:
  - chmod +x monticore-gradle/gradlew
  - chmod +x monticore-generator/it/experiments/gradlew
  - chmod +x monticore-generator/it/gradlew
  - chmod +x monticore-templateclassgenerator/it/monticore-templateclassgenerator-it/gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .m2/
    - .gradle/wrapper
    - .gradle/caches
  key: ${CI_COMMIT_REF_SLUG} # Cache per branch

stages:
  - build
  - test

build_dev:
  stage: build
  script:
    - "mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS deploy -Dpass=$password -Duser=$username -DdeployAtEnd=true"
    - cd monticore-gradle
    - "./gradlew build"
    - "./gradlew publish -PmavenPassword=$password -PmavenUser=$username"
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, "instructions covered"; print 100*covered/instructions, "% covered" }' ../*/target/site/jacoco/jacoco.csv
  coverage: '/\d+.\d+ \% covered/'
  only:
    - dev
    - cibuild
  artifacts:
    paths:
      - "*/target"
    expire_in: 1 week
    
build_branches:
  stage: build
  script:
    - "mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS install"
  except:
    - dev
    - master

integration-test:
  stage: test
  dependencies: []
  script:
    - cd monticore-generator/it
    - "mvn --settings ../../settings.xml $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS clean verify"
    - "mvn --settings ../../settings.xml $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS clean verify -P emf-it-tests"

it-gradle:
  stage: test
  dependencies: []
  script:
    - cd monticore-generator/it
    - "./gradlew build"
    - "./gradlew build -PbuildProfile=emf"
    - "cd ../../monticore-templateclassgenerator/it/monticore-templateclassgenerator-it"
    - "./gradlew build"
  only:
    - dev

it-experiments-gradle:
  stage: test
  dependencies: []
  script:
    - cd monticore-generator/it/experiments
    - "./gradlew build"
  allow_failure: true
  only:
    - dev

trigger-automata:
  stage: test
  trigger:
    project: monticore/languages/automaton
    branch: master
  only:
    - dev

trigger-cd4a:
  stage: test
  trigger:
    project: monticore/cd4analysis/cd4analysis
    branch: develop
  only:
    - dev